import{i as a,S as m}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function l(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function c(r){if(r.ep)return;r.ep=!0;const e=l(r);fetch(r.href,e)}})();const s={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),formInput:document.querySelector(".form-input"),btn:document.querySelector(".button"),container:document.querySelector(".container"),cssLoader:document.querySelector("#span-loader")};function f(){s.cssLoader.classList.add("loader")}function u(){s.cssLoader.classList.remove("loader")}function d(n){if(n==="")return u(),a.error({message:"Form field must be filled in",position:"topRight"});const t="https://pixabay.com/api/",l="?key=42450434-3c949e4f0cfd845cc919e9207",c=`&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`,r=t+l+c;fetch(r).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0)a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const i=e.hits.map(o=>`<li class="gallery-item">
          <a href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <div class="text">
          <p><b>Likes </b>${o.likes}</p>
          <p><b>Views </b>${o.views}</p>
          <p><b>Comments </b>${o.comments}</p>
          <p><b>Downloads </b>${o.downloads}</p>
          </div>
          </li>`).join("");s.gallery.insertAdjacentHTML("afterbegin",i),new m(".gallery a",p).refresh()}}).catch(e=>console.log("Error:",e)).finally(()=>{u()})}const p={captionsData:"alt",captionDelay:250};function g(n){n.preventDefault(),f(),s.gallery.innerHTML="";const t=s.formInput.value.trim();d(t),s.form.reset()}s.form.addEventListener("submit",g);
//# sourceMappingURL=commonHelpers.js.map
